### ISSUE TITLE
Error ‘CA_SET_DESCR_DATA’ undeclared (first use in this function) in dvb_ca.c

### ISSUE THREAD

**Issue by halinka1125** [Duckbox-Developers/StartHere#4]
Hello
I have compile error on ADB_BOX, SPARK_7162 platfom. This is error in file, or I doing something wrong?
Os 40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux

"/github/StartHere/cdk$ make yaud-enigma2-pli-nightly
cp /home/xxx/github/StartHere/driver/stgfb/stmfb/linux/drivers/video/stmfb.h /home/xxx/github/StartHere/tufsbox/cdkroot/usr/include/linux
cp /home/xxx/github/StartHere/driver/player2/linux/include/linux/dvb/stm_ioctls.h /home/xxx/github/StartHere/tufsbox/cdkroot/usr/include/linux/dvb
make -C /home/xxx/github/StartHere/driver ARCH=sh \
                CONFIG_MODULES_PATH=/home/xxx/github/StartHere/tufsbox/cross/target \
                KERNEL_LOCATION=/home/xxx/github/StartHere/cdk/linux-sh4-2.6.32.59_stm24_0211 \
                DRIVER_TOPDIR=/home/xxx/github/StartHere/driver \
                                    ADB_BOX=adb_box                 WLANDRIVER=wlandriver PLAYER191=player191 \
                CROSS_COMPILE=sh4-linux-
make[1]: Wejście do katalogu `/home/xxx/github/StartHere/driver'
make[2]: Wejście do katalogu `/home/xxx/github/StartHere/cdk/linux-sh4-2.6.32.59_stm24_0211'
  CC [M]  /home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.o
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c: In function ‘CaIoctl’:
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:242:8: error: ‘CA_SET_DESCR_DATA’ undeclared (first use in this function)
   case CA_SET_DESCR_DATA:
        ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:242:8: note: each undeclared identifier is reported only once for each function it appears in
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:246:4: error: unknown type name ‘ca_descr_data_t’
    ca_descr_data_t *descr = (ca_descr_data_t*) Parameter;
    ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:246:30: error: ‘ca_descr_data_t’ undeclared (first use in this function)
    ca_descr_data_t *descr = (ca_descr_data_t*) Parameter;
                              ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:246:46: error: expected expression before ‘)’ token
    ca_descr_data_t *descr = (ca_descr_data_t*) Parameter;
                                              ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:248:13: error: request for member ‘index’ in something not a structure or union
    if (descr->index & 0x100)
             ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:250:10: error: request for member ‘index’ in something not a structure or union
     descr->index &= 0xFF;
          ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:251:18: error: request for member ‘index’ in something not a structure or union
     sess += descr->index;
                  ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:252:29: error: request for member ‘index’ in something not a structure or union
     altDescr += 1000 * descr->index;
                             ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:255:13: error: request for member ‘index’ in something not a structure or union
    if (descr->index >= 16)
             ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:257:13: error: request for member ‘parity’ in something not a structure or union
    if (descr->parity > 1)
             ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:268:13: error: request for member ‘index’ in something not a structure or union
    if (descr->index < 0 || descr->index >= NUMBER_OF_DESCRAMBLERS)
             ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:268:33: error: request for member ‘index’ in something not a structure or union
    if (descr->index < 0 || descr->index >= NUMBER_OF_DESCRAMBLERS)
                                 ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:270:86: error: request for member ‘index’ in something not a structure or union
     printk("Error descrambler %d not supported! needs to be in range 0 - %d\n", descr->index, NUMBER_OF_DESCRAMBLERS - 1);
                                                                                      ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:276:58: error: request for member ‘data’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(sess, altDescr, descr->data, descr->parity, descr->data_type) != 0)
                                                          ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:276:71: error: request for member ‘parity’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(sess, altDescr, descr->data, descr->parity, descr->data_type) != 0)
                                                                       ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:276:86: error: request for member ‘data_type’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(sess, altDescr, descr->data, descr->parity, descr->data_type) != 0)
                                                                                      ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:279:84: error: request for member ‘index’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(pSession->session, pSession->descramblers[descr->index], descr->data, descr->parity, descr->data_type) != 0)
                                                                                    ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:279:99: error: request for member ‘data’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(pSession->session, pSession->descramblers[descr->index], descr->data, descr->parity, descr->data_type) != 0)
                                                                                                   ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:279:112: error: request for member ‘parity’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(pSession->session, pSession->descramblers[descr->index], descr->data, descr->parity, descr->data_type) != 0)
                                                                                                                ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:279:127: error: request for member ‘data_type’ in something not a structure or union
     if (pti_hal_descrambler_set_aes(pSession->session, pSession->descramblers[descr->index], descr->data, descr->parity, descr->data_type) != 0)
                                                                                                                               ^
/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.c:244:8: warning: unused variable ‘i’ [-Wunused-variable]
    int i, altDescr = 40000, sess = 10000;
        ^
make[6]: *** [/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb/dvb_ca.o] Błąd 1
make[5]: *** [/home/xxx/github/StartHere/driver/player2/linux/drivers/media/dvb/stm/dvb] Błąd 2
make[4]: *** [/home/xxx/github/StartHere/driver/player2/linux] Błąd 2
make[3]: *** [/home/xxx/github/StartHere/driver/player2] Błąd 2
make[2]: *** [_module_/home/xxx/github/StartHere/driver] Błąd 2
make[2]: Opuszczenie katalogu `/home/xxx/github/StartHere/cdk/linux-sh4-2.6.32.59_stm24_0211'
make[1]: *** [all] Błąd 2
make[1]: Opuszczenie katalogu `/home/xxx/github/StartHere/driver'
make: *** [.deps/driver] Błąd 2"

**Comment by TangoCash** [comment]
Patchlevel 211 is outdated, Please try 215 or 217

**Comment by halinka1125** [comment]
I know but for tuner 25 (PKT ADB 5800) is no patch...

**Comment by TangoCash** [comment]
I updated p211 - e2 tree, please pull and try again

**Comment by halinka1125** [comment]
Till now compiling good, I give response after compilation. But I assume it is fixed.
THANK YOU!!!

**Comment by halinka1125** [comment]
OK now I have compiled, python-wifi only was not downloaded,because source doesn't exist.
**Big thanks for support **

Similar problem python-wifi_0.5.0.bb download source:
https://github.com/OpenPLi/openpli-oe-core/pull/8/commits/1d3a0b66e0fd09bd0df327e73690c2e486ba297e

**Comment by TangoCash** [comment]
Thy for reporting, all patchlevel fixed, python wifi bump to newwest verion, dl link fixed :)
